# Generated by Django 4.2 on 2023-07-21 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bookmarked',
            field=models.ManyToManyField(related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
