# Generated by Django 4.2 on 2023-08-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='display_order',
            field=models.IntegerField(unique=True),
        ),
    ]
