# Generated by Django 4.2 on 2023-08-06 17:08

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=personal.models.upload_location)),
                ('education', models.TextField()),
                ('title', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('detail', models.TextField()),
            ],
        ),
    ]
