# Generated by Django 4.2 on 2023-07-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preposttest', '0002_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preposttest.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preposttest.question')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPrePostTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('answers', models.ManyToManyField(through='preposttest.QuestionAnswer', to='preposttest.question')),
                ('pre_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preposttest.pretest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preposttest.resultpreposttest'),
        ),
    ]
