# Generated by Django 4.2 on 2023-07-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0003_questionanswer_resultpreposttest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultpreposttest',
            name='score',
            field=models.FloatField(),
        ),
    ]
