# Generated by Django 4.2 on 2023-07-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0004_alter_resultpreposttest_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='MultipleChoiceQuestion',
        ),
    ]
