# Generated by Django 4.2 on 2023-07-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0005_rename_question_multiplechoicequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretest',
            old_name='number_of_questions',
            new_name='number_of_mcq',
        ),
    ]
