# Generated by Django 4.2 on 2023-07-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0008_essayquestion_essayanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essayanswer',
            old_name='essay',
            new_name='test',
        ),
    ]
