# Generated by Django 4.2 on 2023-07-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0010_rename_test_essayanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='created',
        ),
    ]
