# Generated by Django 4.2 on 2023-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0012_essayanswer_result_resultpreposttest_essayanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretest',
            name='test_type',
            field=models.CharField(choices=[('pretest', 'Pretest'), ('posttest', 'Posttest')], default='pretest', max_length=10),
        ),
    ]
