# Generated by Django 4.2 on 2023-07-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preposttest', '0013_pretest_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretest',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pretest',
            name='title',
        ),
    ]
